import React, { useState } from 'react';
import { CheckCircle2, ShieldCheck, XCircle } from 'lucide-react';
import { RecoveryIncident } from '../types';

interface RecoveryCheckoutProps {
  incident: RecoveryIncident;
  onClose: () => void;
  onPaymentRecovered: (incident: RecoveryIncident) => void;
}

export const RecoveryCheckout: React.FC<RecoveryCheckoutProps> = ({
  incident,
  onClose,
  onPaymentRecovered,
}) => {
  const [isProcessing, setIsProcessing] = useState(false);
  const [isComplete, setIsComplete] = useState(false);

  const handlePayment = () => {
    setIsProcessing(true);

    setTimeout(() => {
      setIsProcessing(false);
      setIsComplete(true);

      setTimeout(() => {
        onPaymentRecovered(incident);
      }, 1200);
    }, 1200);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="w-full max-w-md bg-white rounded-2xl shadow-2xl overflow-hidden">

        {/* Header */}
        <div className="bg-slate-900 text-white px-6 py-5">
          <div className="flex items-center justify-between">
            <div>
              <div className="text-xs text-slate-400 font-semibold uppercase tracking-wider">
                RecoverAI
              </div>

              <h2 className="text-xl font-bold mt-1">
                Secure Recovery Checkout
              </h2>
            </div>

            <button
              onClick={onClose}
              className="p-2 rounded-lg hover:bg-white/10 transition"
            >
              <XCircle className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="p-6">

          {isComplete ? (
            <div className="text-center py-8">

              <CheckCircle2 className="w-16 h-16 text-emerald-500 mx-auto mb-4" />

              <h3 className="text-2xl font-bold text-slate-900">
                Payment Recovered
              </h3>

              <p className="text-sm text-slate-500 mt-2">
                Simulated settlement confirmed successfully.
              </p>

              <div className="mt-6 bg-emerald-50 border border-emerald-200 rounded-xl p-4">
                <div className="text-xs text-emerald-700 font-semibold">
                  RECOVERY COMPLETE
                </div>

                <div className="text-2xl font-bold text-emerald-800 mt-1">
                  {incident.currency}{incident.amount.toLocaleString()}
                </div>
              </div>

            </div>
          ) : (
            <>
              {/* Demo badge */}
              <div className="flex items-center gap-2 bg-blue-50 border border-blue-200 rounded-lg px-3 py-2 mb-5">
                <ShieldCheck className="w-4 h-4 text-blue-600" />

                <span className="text-xs font-semibold text-blue-700">
                  Demo • No real payment will be processed
                </span>
              </div>

              {/* Incident */}
              <div className="space-y-4">

                <div>
                  <div className="text-xs text-slate-400 uppercase font-semibold">
                    Recovery Incident
                  </div>

                  <div className="text-sm font-bold text-slate-900 mt-1">
                    {incident.id}
                  </div>
                </div>

                <div>
                  <div className="text-xs text-slate-400 uppercase font-semibold">
                    Customer
                  </div>

                  <div className="text-sm font-semibold text-slate-900 mt-1">
                    {incident.customerName}
                  </div>
                </div>

                <div>
                  <div className="text-xs text-slate-400 uppercase font-semibold">
                    Recovery Amount
                  </div>

                  <div className="text-3xl font-bold text-slate-900 mt-1">
                    {incident.currency}{incident.amount.toLocaleString()}
                  </div>
                </div>

                <div className="bg-slate-50 border border-slate-200 rounded-xl p-4">
                  <div className="text-sm font-semibold text-slate-900">
                    Secure Recovery Payment
                  </div>

                  <p className="text-xs text-slate-500 mt-1">
                    This simulated checkout was generated by RecoverAI
                    after detecting a revenue-at-risk event.
                  </p>
                </div>

              </div>

              {/* Payment button */}
              <button
                onClick={handlePayment}
                disabled={isProcessing}
                className="w-full mt-6 bg-slate-900 hover:bg-slate-800 disabled:bg-slate-400 text-white font-semibold py-3.5 rounded-xl transition"
              >
                {isProcessing
                  ? 'Processing Simulated Payment...'
                  : 'Complete Simulated Payment'}
              </button>

              <button
                onClick={onClose}
                disabled={isProcessing}
                className="w-full mt-2 py-3 text-sm font-semibold text-slate-500 hover:text-slate-800 transition"
              >
                Cancel
              </button>
            </>
          )}

        </div>
      </div>
    </div>
  );
};